Salut moi je m'appelle Jonathan Mudiambat je suis développeur Python et Aspirant machine learning specialist.
Je te partage ce notebook qui engloble l'essentiel sur la programmation Python

No

#Python

Un langage de programmation est un ensemble de règles et de conventions permettant à un programmeur de communiquer des instructions à un ordinateur, facilitant ainsi le développement de logiciels.

Il existe plusieurs types de langages de programmation, classés généralement en deux catégories principales : les langages de bas niveau et les langages de haut niveau.Langages de bas niveau :Langage machine : Composé de codes binaires, il est directement compréhensible par le processeur.Langage d'assemblage : Utilise des mnémoniques représentant les instructions du langage machine.Langages de haut niveau :Langages impératifs : Comme C, C++, Java, et Python, définissent séquentiellement les étapes à suivre pour atteindre un résultat.Langages déclaratifs : Comme SQL, spécifient le résultat souhaité sans détailler la séquence d'instructions.Langages orientés objet : Comme Java, Python, et C#, organisent le code en objets pour encapsuler des fonctionnalités.Chaque type de langage a ses avantages et inconvénients, adaptés à différents contextes et besoins de programmation.

Un langage interprété est un langage de programmation dont le code source est directement exécuté par un interpréteur, sans nécessiter une étape de compilation préalable. Contrairement aux langages compilés, tels que C++ ou Java, où le code source est transformé en langage machine avant l'exécution, les langages interprétés sont interprétés ligne par ligne au moment de l'exécution. Exemples de langages interprétés incluent Python, JavaScript et Ruby.

Python est un langage de programmation interprété, polyvalent et haut niveau. Conçu pour favoriser la lisibilité du code, il utilise une syntaxe claire et concise. Python prend en charge différents paradigmes de programmation, notamment impératif, orienté objet et fonctionnel. Il est largement utilisé dans le développement web, la science des données, l'automatisation de tâches, l'intelligence artificielle et bien d'autres domaines en raison de sa facilité d'apprentissage et de son vaste écosystème de bibliothèques.

#les concepts clés

1. Une variable en programmation est un espace de stockage qui a un nom symbolique (identificateur) et une valeur associée. Elle permet de représenter et de manipuler des données dans un programme. Le contenu d'une variable peut changer au cours de l'exécution du programme. En fonction du langage de programmation, les variables peuvent avoir des types de données spécifiques, tels que entier, chaîne de caractères, flottant, etc. L'utilisation appropriée des variables est essentielle pour stocker et gérer l'information de manière efficace dans un programme.

In [ ]:
#Exemples

Age = 30
Nom = 'Jonathan'
Point = 75.5

#Types de variables en Python

Le type Int (entier) stock des nombres entiers

In [ ]:
Age = 30
Prix = 1000
Numero = 8147272

Le type float (décimal) stock le nombre décimal

In [ ]:
Point = 78.5
Prix = 45.5
Distance = 57.780

Le type string (str ou chaîne de caractères) stock une chaîne de caractère ou des nombres entre '' ou ""

In [ ]:
Nom = 'joyce'
Matricule = "A1234"
Message = "hello world"

#Comment afficher un message dans la console (le fameux "hello world")

Pour afficher un message dans la console on utilise la fonction print() et le message entre ()

In [ ]:
print("bonjour à tous ")

bonjour à tous 


#Pourquoi apprendre Python actuellement ?

- Polyvalence : Python est un langage polyvalent utilisé dans des domaines tels que le développement web, la science des données, l'intelligence artificielle, l'automatisation, le développement de jeux, etc.
-Facilité d'apprentissage : La syntaxe claire et lisible de Python en fait un choix idéal pour les débutants. Son apprentissage est souvent considéré comme plus accessible que certains autres langages.
-Écosystème riche : Python dispose d'une vaste bibliothèque standard et d'une communauté active qui propose de nombreux modules et frameworks, facilitant le développement de projets divers.
- Science des données et IA : Python est largement utilisé dans le domaine de la science des données avec des bibliothèques telles que NumPy, Pandas et Matplotlib. Il est également populaire pour le machine learning avec des frameworks comme TensorFlow et PyTorch.
-Automatisation : Python est utilisé pour automatiser des tâches répétitives et simplifier des processus grâce à des bibliothèques telles que Selenium et BeautifulSoup.Adoption par les grandes entreprises : De nombreuses grandes entreprises utilisent Python, ce qui renforce sa pertinence sur le marché de l'emploi.

#Plan d'apprentissage

1.les variables

2.les chaînes de caractères

3.les structures de données

4.les contrôles de flux

5.les fonctions

6.les classes

7.les exceptions

Les modules et bibliothèques

Challenges

#variabes

Determine le type d'une variable

In [ ]:
Age = 30
print(type(Age))

<class 'int'>


In [ ]:
Point = 56.76
print (type (Point))

<class 'float'>


Les opérations Mathématiques en Python

In [ ]:
a = 35
b = 35.45
print(b + a)

70.45


In [ ]:

print(a-b)

-0.45000000000000284


In [ ]:
print(a/b)
print(a*b)
print(3%4)
print(2**3)

0.9873060648801127
1240.75
3
8


Le f-string(f'') permet s'afficher le variable d'une façon concise

In [ ]:
nom = 'Jonathan'
age = 26
print(f"bonjour je suis {nom} et j'ai {age} ans")

bonjour je suis Jonathan et j'ai 26 ans


Le symbole = permet d'affecter une valeur
== permet de faire une comparaison et renvoie un type de variable appelé booleens qui prend deux valeurs true ou false

In [ ]:

a = 10
b= 5
print(a > b)

True


Concatenation permet l'Union de deux chaîne de caractères

In [ ]:
nom = 'Joy'
post  = 'ce'
print(nom+ post)

Joyce


In [ ]:
print(type(nom))

<class 'str'>


#Quelques points à retenir sur les variables

1.Déclaration et Assignation : Les variables sont créées en assignant une valeur à un nom. Exemple : x = 10.

2.Types de Données : Les variables peuvent contenir différents types de données comme les entiers (int), les nombres à virgule flottante (float), les chaînes de caractères (str), etc.

3.Dynamiquement typé : Python est un langage typé dynamiquement, ce qui signifie que le type d'une variable peut changer pendant l'exécution du programme.

4.Nom de Variable : Les noms de variables commencent par une lettre (a-z, A-Z) ou un souligné (_) suivi de lettres, chiffres ou soulignés.

5.Sensibilité à la Casse : Python est sensible à la casse, donc maVariable et MaVariable sont deux variables distinctes.

6.Opérations sur les Variables : Vous pouvez effectuer des opérations arithmétiques sur les variables, comme l'addition, la soustraction, la multiplication, etc.

7.Modification de Valeurs : Les valeurs des variables peuvent être modifiées en réassignant une nouvelle valeur au même nom de variable.

8.Affichage : Utilisez la fonction print() pour afficher la valeur d'une variable.

En Python, les booléens sont un type de données qui peut avoir deux valeurs : True (Vrai) ou False (Faux). Ces valeurs sont souvent utilisées dans les expressions conditionnelles pour prendre des décisions dans le code. Par exemple :

In [ ]:
est_vrai = True
est_faux = False

if est_vrai:
    print("C'est vrai!")

if not est_faux:
    print("Ce n'est pas faux!")

C'est vrai!
Ce n'est pas faux!


Les opérations booléennes telles que and (et), or (ou) et not (non) sont également utilisées pour combiner ou inverser des booléens dans des expressions logiques.

In [ ]:
nom = 'Jonathan'
post = 'jonathan'
print(nom == post)

False


In [ ]:
Nom = 'Joyce'
nom = 'Joyce'

Exercises

1.determiner le périmètre et la surface d'un carré dont le côté vaut 5 cm

In [ ]:
cote = 5
perimeter = cote * 4
print(perimeter)
print(f" Le périmètre de mon carré vaut {perimeter} cm")

20
 Le périmètre de mon carré vaut 20 cm


In [ ]:
cotecote = 5
surface = cote*cote
surfac fte1 = cote**2

print(surface)
print(surface1)

25
25


#Les chaînes de caractères ou str

1. Déclaration de chaînes : Vous pouvez déclarer une chaîne en utilisant des guillemets simples (') ou doubles (").

2. Indexation : Les caractères d'une chaîne peuvent être accédés par leur indice, commençant à 0. Exemple : premier_char = chaine[0]

3. Longueur de la chaîne : Utilisez la fonction len() pour obtenir la longueur d'une chaîne. Exemple : longueur = len(chaine)

4. Concaténation : Les chaînes peuvent être concaténées avec l'opérateur +. Exemple : nouvelle_chaine = chaine1 + chaine2

5. Représentation brute : Vous pouvez obtenir la représentation brute d'une chaîne en utilisant la fonction repr(). Exemple : representation = repr(chaine)

6. Opérations de base : Les chaînes supportent des opérations telles que la multiplication (*) pour répéter une chaîne.

7. Slicing : Vous pouvez extraire des sous-chaînes en utilisant la notation de découpage. Exemple : sous_chaine = chaine[1:4]

8. Méthodes de chaînes : Les chaînes ont plusieurs méthodes utiles telles que upper(), lower(), strip(), etc.

9. Formatage de chaînes : Vous pouvez formater des chaînes avec des méthodes comme format() ou les f-strings (à partir de Python 3.6).

10. Immutabilité : Une fois créée, une chaîne ne peut pas être modifiée. Les opérations comme la concaténation créent de nouvelles chaînes.

11. Comparaison de chaînes : Les opérateurs de comparaison (==, !=, <, >, <=, >=) peuvent être utilisés pour comparer des chaînes.

12. Échappement de caractères : Certains caractères spéciaux nécessitent un échappement avec le caractère \, par exemple, \" pour représenter une double guillemet.

In [ ]:
nom = 'Jonathan'
print(nom[0])

J


In [ ]:
print(len(nom))

8


In [ ]:
print(nom.upper())

JONATHAN


In [ ]:
print(nom.lower())

jonathan


In [ ]:
print(nom.split('a'))

['Jon', 'th', 'n']


In [ ]:
print(nom.count('o'))

1


#les structures de contrôle de flux

En Python, les structures de contrôle de flux permettent de gérer l'exécution conditionnelle et répétitive du code. Voici quelques-unes des principales structures de contrôle :Conditionnelle avec if, elif et else :

if condition1:
    # Code exécuté si condition1 est vraie
elif condition2:
    # Code exécuté si condition1 est fausse et condition2 est vraie
else:
    # Code exécuté si toutes les conditions précédentes sont Fausses```

 Boucle for pour l'itération sur une séquence (liste, tuple, chaîne de caractères, etc.) :

for element in sequence:
    # Code exécuté pour chaque élément dans la séquenceBoucle while pour l'itération basée sur une condition :while condition:
    # Code exécuté tant que la condition est vraie

Instructions break et continue :break : interrompt immédiatement la boucle.

continue : passe à l'itération suivante de la boucle.

Compréhensions de liste : Permet de créer des listes de manière concise en utilisant une syntaxe compacte.

squares = [x**2 for x in range(10)]

Ces structures offrent une flexibilité significative pour contrôler le flux d'exécution dans vos programmes Python.

In [ ]:
a = 4
if a == 5:
   print('hello world')
else:
   print('bonjour')

hello world


In [ ]:

name = 'jonathan'
for i in name:
   print(i )

j
o
n
a
t
h
a
n


La boucle while permet d'effectuer de répéter un bout de code si une condition est respecter

In [ ]:
a = 0
while a < 5:
    print(a)
    a += 1

0
1
2
3
4


#les listes

En Python, les listes sont des structures de données permettant de stocker une collection ordonnée d'éléments.

Vous pouvez créer une liste en utilisant des crochets [] et en séparant les éléments par des virgules. Voici un exemple simple :

ma_liste = [1, 2, 3, 4, 5]

Vous pouvez accéder aux éléments de la liste en utilisant leur indice, en commençant par 0. Par exemple,

 ma_liste[0] renverra 1.

Vous pouvez également effectuer des opérations telles que l'ajout d'éléments à une liste avec la méthode append :

ma_liste.append(6)

Cela ajoutera l'élément 6 à la fin de la liste.

Les listes peuvent contenir des éléments de différents types, y compris d'autres listes, ce qui les rend très flexibles.

liste_mixte = [1, "deux", 3.0, [4, 5]]

N'oubliez pas que les indices négatifs commencent par la fin de la liste. Par exemple, -1 fait référence au dernier élément.

dernier_element = ma_liste[-1]

En outre, vous pouvez utiliser des opérations de découpage (slicing) pour extraire des sous-listes.

 Par exemple, ma_liste[1:3] renverra une nouvelle liste contenant les éléments à l'indice 1 et 2.

Les listes offrent de nombreuses autres fonctionnalités, comme le tri, la recherche d'éléments, etc.

In [ ]:
My_list = [1, 2,3,5]
fruits = [ 'pomme', 'orange', 'pommes']

In [ ]:
fruits.append('citron')
print(fruits)

['pomme', 'orange', 'pommes', 'citron']


In [ ]:
fruits[3]

'citron'

La méthode extend permet d'étendre une liste avec des iterables

In [ ]:
liste1 = [1, 2, 3]
liste2 = [4, 5, 6]

liste1.extend(liste2)

print(liste1)

[1, 2, 3, 4, 5, 6]


La méthode remove en Python est utilisée pour supprimer la première occurrence d'un élément spécifié dans une liste. Voici un exemple d'utilisation de la méthode remove :

In [ ]:
ma_liste = [1, 2, 3, 2, 4]

ma_liste.remove(2)

print(ma_liste)

[1, 3, 2, 4]


La méthode insert(i, x): Insère un élément à une position spécifique dans la liste.
Avec i qui est la position et x l'élément

In [ ]:
ma_liste = [1, 2, 3]
ma_liste.insert(1, 4)# Insère 4 à l'indice 1
print(ma_liste)

[1, 4, 2, 3]


La méthode pop est utilisée pour supprimer et renvoyer un élément d'une liste à une position spécifique.

In [ ]:
ma_liste = [1, 2, 3, 4, 5]
element_supprime = ma_liste.pop(2)
print(ma_liste)

[1, 2, 4, 5]


Si aucun indice n'est spécifié, la méthode pop supprimera et renverra le dernier élément de la liste par défaut.

In [ ]:
ma_liste = [1, 2, 3, 4, 5]
dernier_element = ma_liste.pop()
print(ma_liste)

[1, 2, 3, 4]


#Utilisation d'une boucle for pour créé une suite des nombre de 0 à 10

In [ ]:
# Création de la liste vide
ma_liste = []

# Ajout des nombres de 0 à 10 à la liste
for nombre in range(10):
    ma_liste.append(nombre)

# Affichage de la liste résultante
print(ma_liste)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


#Exercices

Exercice 1 - Manipulation de chaînes :

1. Créez une chaîne de caractères.

2. Imprimez la longueur de la chaîne.

3. Imprimez la première moitié de la chaîne.

4. Imprimez la chaîne en majuscules.

In [ ]:
# Créez une chaîne de caractères
ma_chaine = "Exemple de chaîne"

# Imprimez la longueur de la chaîne
print(len(ma_chaine))

# Imprimez la première moitié de la chaîne
moitie = len(ma_chaine) // 2
print(ma_chaine[:moitie])

# Imprimez la chaîne en majuscules
print(ma_chaine.upper())

17
Exemple 
EXEMPLE DE CHAÎNE


Exercice 2 - Boucles et listes :

1. Créez une liste de nombres de 1 à 10.
2. Utilisez une boucle pour imprimer chaque nombre multiplié par 2.

In [ ]:
# Créez une liste de nombres de 1 à 10
liste_nombres = list(range(1, 11))

# Utilisez une boucle pour imprimer chaque nombre multiplié par 2
for nombre in liste_nombres:
    print(nombre * 2)

2
4
6
8
10
12
14
16
18
20


Exercice 3 - Manipulation de listes :

1. Créez deux listes de même longueur.
2. Concaténez-les pour former une nouvelle liste.
3. Ajoutez un élément à la fin de la nouvelle liste.
4. Supprimez le deuxième élément de la nouvelle liste.

In [ ]:
# Créez deux listes de même longueur
liste1 = [1, 2, 3, 4]
liste2 = [5, 6, 7, 8]

# Concaténez-les pour former une nouvelle liste
nouvelle_liste = liste1 + liste2

# Ajoutez un élément à la fin de la nouvelle liste
nouvelle_liste.append(9)

# Supprimez le deuxième élément de la nouvelle liste
del nouvelle_liste[1]

# Affichez la nouvelle liste résultante
print(nouvelle_liste)

[1, 3, 4, 5, 6, 7, 8, 9]


Exercice 4 - Boucle et chaînes de caractères :

1. Créez une chaîne de caractères.
2. Utilisez une boucle pour imprimer chaque caractère séparément.

In [ ]:
#la chaîne
chaine = "bonjour les amis"
#iterer sur la chaîne de caractères
for i in chaine :
   print(i)

b
o
n
j
o
u
r
 
l
e
s
 
a
m
i
s


Exercice 5 - Recherche dans une liste :

1. Créez une liste de noms.
2. Utilisez une boucle pour vérifier si un nom donné est présent dans la liste.
3. Imprimez un message approprié en fonction du résultat.

In [ ]:
# Créez une liste de noms
liste_noms = ["Alice", "Joyce", "Charlie", "David"," Jonathan"]

# Nom à vérifier
nom_a_verifier = "Joyce"

# Utilisez une boucle pour vérifier si le nom est présent dans la liste
for nom in liste_noms:
    if nom == nom_a_verifier:
        print(f"{nom_a_verifier} est présent dans la liste.")
        break
else:
    print(f"{nom_a_verifier} n'est pas présent dans la liste.")

Joyce est présent dans la liste.


Exercice 6 - Manipulation de chaînes et boucles :

1. Créez une chaîne de caractères contenant des mots séparés par des espaces.
2. Utilisez une boucle pour compter le nombre de mots dans la chaîne.

In [ ]:
# Créez une chaîne de caractères contenant des mots séparés par des espaces
chaine_de_mots = "Ceci est une chaîne de caractères avec plusieurs mots"

# Utilisez une boucle pour compter le nombre de mots dans la chaîne
nombre_de_mots = 0
for mot in chaine_de_mots.split():
    nombre_de_mots += 1

# Imprimez le nombre de mots
print(f"Le nombre de mots dans la chaîne est : {nombre_de_mots}")

Le nombre de mots dans la chaîne est : 9


Exercice 7 - Création de listes avec conditions :

1. Créez une liste de nombres de 1 à 20.
2. Utilisez une boucle pour créer une nouvelle liste contenant uniquement les nombres pairs.

In [ ]:
# Créez une liste de nombres de 1 à 20
liste_nombres = list(range(1, 21))

# Utilisez une boucle pour créer une nouvelle liste contenant uniquement les nombres pairs
nouveaux_nombres_pairs = [nombre for nombre in liste_nombres if nombre % 2 == 0]

# Imprimez la nouvelle liste
print(nouveaux_nombres_pairs)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


#Les dictionnaires

un dictionnaire est une structure de données qui permet de stocker des paires clé-valeur. Chaque élément dans un dictionnaire est associé à une clé unique qui permet d'accéder à la valeur correspondante. Voici un exemple simple de création et d'utilisation d'un dictionnaire en Python :

In [ ]:
# Créez un dictionnaire avec quelques paires clé-valeur
mon_dictionnaire = {
    "nom": "John",
    "age": 25,
    "ville": "Paris"
}

# Accédez à la valeur en utilisant la clé
nom_utilisateur = mon_dictionnaire["nom"]
age_utilisateur = mon_dictionnaire["age"]

# Modifiez une valeur existante
mon_dictionnaire["age"] = 26

# Ajoutez une nouvelle paire clé-valeur
mon_dictionnaire["profession"] = "Ingénieur"

# Supprimez une paire clé-valeur
del mon_dictionnaire["ville"]

# Parcourez les clés et les valeurs du dictionnaire
for cle, valeur in mon_dictionnaire.items():
    print(f"{cle}: {valeur}")

nom: John
age: 26
profession: Ingénieur


Les méthodes sur les dictionnaires :

La méthode key() : Retourne une vue sur les clés du dictionnaire.

In [ ]:

mon_dict = {"nom":"Joyce","age":"45"}
clefs = mon_dict.keys()
print(clefs)

dict_keys(['nom', 'age'])


la méthode values(): Retourne une vue sur les valeurs du dictionnaire.

In [ ]:
val = mon_dict.values()
print(val)

dict_values(['Joyce', '45'])


La méthode items(): Retourne une vue sur les paires clé-valeur du dictionnaire.

In [ ]:
Objet = mon_dict.items()
print(Objet)

dict_items([('nom', 'Joyce'), ('age', '45')])


La méthode get(cle, valeur_par_defaut): Retourne la valeur associée à la clé spécifiée, ou une valeur par défaut si la clé n'est pas présente.

In [ ]:
age = mon_dict['age']
age

'45'

La méthode pop(cle, valeur_par_defaut): Supprime et retourne la valeur associée à la clé spécifiée, ou une valeur par défaut si la clé n'est pas présente

In [ ]:
age = mon_dict.pop("age",23)
age

23

La méthode update(dictionnaire): Met à jour le dictionnaire avec les paires clé-valeur d'un autre dictionnaire.

In [ ]:
second_dict = {"etat": "célibataire "," age":"25"}
mon_dict.update (second_dict)
print(mon_dict)

{'nom': 'Joyce', 'etat': 'célibataire ', ' age': '25'}


Notes

1. Structure clé-valeur : Chaque élément dans un dictionnaire est constitué d'une clé unique associée à une valeur. Les clés sont souvent des chaînes de caractères, mais peuvent être de divers types immuables tels que les entiers, les tuples, etc.

2. Syntaxe : La syntaxe pour créer un dictionnaire utilise des accolades {}. Les paires clé-valeur sont séparées par des virgules, et la clé et la valeur sont séparées par deux-points (:).

3. Accès aux éléments : On accède aux valeurs en utilisant les clés. Par exemple, nom_utilisateur = mon_dictionnaire["nom"] récupère la valeur associée à la clé "nom".

4. Mutabilité : Les dictionnaires sont des structures de données mutables, ce qui signifie que vous pouvez ajouter, modifier et supprimer des éléments après leur création.

5. Méthodes intégrées : Les dictionnaires disposent de méthodes intégrées telles que keys(), values(), items(), get(), etc., qui simplifient la manipulation des données.

6. Flexibilité : Les dictionnaires sont polyvalents et peuvent stocker des données hétérogènes. Les valeurs peuvent être de n'importe quel type, y compris d'autres dictionnaires.

#La différence entre un dictionnaire et une liste

les listes sont adaptées pour des séquences ordonnées d'éléments accessibles par indice, tandis que les dictionnaires sont utilisés pour des associations clé-valeur, fournissant un accès rapide et significatif aux données.

#les tuples et les set(ensemble)

En Python, un tuple est une structure de données similaire à une liste, mais avec une différence clé : les tuples sont immuables. Cela signifie que, une fois créés, les tuples ne peuvent pas être modifiés. Voici quelques caractéristiques importantes des tuples :

In [ ]:
mon_tuple = (1, "abc", 3.14)
mon_tuple

(1, 'abc', 3.14)

Immuabilité : Contrairement aux listes, vous ne pouvez pas ajouter, supprimer ou modifier des éléments dans un tuple après sa création.

Indexation : Les éléments d'un tuple sont accessibles par leur indice, de la même manière que les listes.

In [ ]:
mon_tuple = (1, "abc", 3.14)
premier_element = mon_tuple[0]
premier_element

1

Hétérogénéité : Les tuples peuvent contenir des éléments de types différents.

In [ ]:
un_autre_tuple = ("python", 42, [1, 2, 3])

Longueur fixe : Une fois qu'un tuple est créé, sa longueur ne peut pas être modifiée.

Utilisation : Les tuples sont souvent utilisés lorsque l'ordre des éléments est important, mais l'immutabilité est souhaitée. Par exemple, pour représenter des coordonnées (x, y) ou une date (année, mois, jour).

Voici un exemple d'utilisation de tuples :

In [ ]:
coordonnees = (3, 7)
print(f"Coordonnées x : {coordonnees[0]}, y : {coordonnees[1]}")

Coordonnées x : 3, y : 7


Les différentes méthodes

la méthode count(valeur) : Retourne le nombre d'occurrences de la valeur spécifiée dans le tuple.

In [ ]:
mon_tuple = (1, 2, 2, 3,2, 2, 4)
occ_de_deux = mon_tuple.count(3)
print(occ_de_deux)

1


La méthode index(valeur) : Retourne l'indice de la première occurrence de la valeur spécifiée.

In [ ]:
mon_tuple = (10, 20, 30, 20, 40)
indice = mon_tuple.index(40)
indice

4

len(tuple) : Retourne la longueur (le nombre d'éléments) du tuple.

In [ ]:
longueur = len(mon_tuple)
longueur

5

Conversion entre types : Vous pouvez utiliser les fonctions tuple() pour créer un tuple à partir d'une séquence (par exemple, une liste) et list() pour créer une liste à partir d'un tuple.

In [ ]:
ma_liste = [1, 2, 3]
mon_tuple = tuple(ma_liste)
mon_tuple
print(type(mon_tuple))

<class 'tuple'>


#les sets

En Python, un ensemble (set) est une structure de données qui représente une collection non ordonnée d'éléments uniques. Les sets sont utiles pour effectuer des opérations mathématiques telles que l'union, l'intersection, la différence, etc. Voici quelques caractéristiques importantes des sets :

1. Syntaxe : Les sets sont définis en utilisant des accolades {}.

In [ ]:
mon_set = {1, 2, 3, 4, 5}
mon_set.add(5)
print(mon_set)

{1, 2, 3, 4, 5}


2. Éléments uniques : Les sets ne peuvent pas contenir d'éléments en double. Si vous ajoutez un élément déjà présent, il ne sera pas ajouté une deuxième fois.

3. Immuabilité : Les sets sont mutables, c'est-à-dire que vous pouvez ajouter et supprimer des éléments après leur création. Cependant, les éléments individuels doivent être immuables (comme les nombres, les chaînes ou les tuples).

In [ ]:
mon_set.add(6)    # Ajoute un élément
mon_set.remove(1) # Supprime un élément

Opérations ensemblistes : Les sets supportent des opérations ensemblistes telles que l'union, l'intersection, la différence, etc

In [ ]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}

union_set = set1.union(set2)         # Union
intersection_set = set1.intersection(set2) # Intersection
difference_set = set1.difference(set2)# Différence

print(intersection_set)
print(difference_set)

{3}
{1, 2}


Conversion entre types : Vous pouvez utiliser la fonction set() pour créer un set à partir d'une séquence (par exemple, une liste).

In [ ]:
ma_liste = [1, 2, 3, 3, 4]
mon_set = set(ma_liste)

Les méthodes de set

La méthode add(element) : Ajoute un élément à l'ensemble. Si l'élément est déjà présent, il n'est pas ajouté une deuxième fois.

In [ ]:
mon_set = {1, 2, 3}
mon_set.add(4)
mon_set

{1, 2, 3, 4}

La méthode remove(element) : Supprime un élément de l'ensemble. Si l'élément n'est pas présent, une erreur est levée.

In [ ]:
mon_set = {1, 2, 3}
mon_set.remove(2)
mon_set

{1, 3}

La méthode discard(element) : Supprime un élément de l'ensemble s'il est présent. Si l'élément n'est pas présent, aucune erreur n'est levée.

In [ ]:
mon_set = {1, 2, 3}
mon_set.discard(2)
mon_set

{1, 3}

La méthode union(other_set) : Retourne un nouvel ensemble contenant tous les éléments des deux ensembles (union).

In [ ]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}
union_set = set1.union(set2)
union_set

{1, 2, 3, 4, 5}

La méthode intersection(other_set) : Retourne un nouvel ensemble contenant les éléments communs aux deux ensembles (intersection).

In [ ]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}
intersection_set = set1.intersection(set2)
intersection_set

{3}

La méthode difference(other_set) : Retourne un nouvel ensemble contenant les éléments de l'ensemble initial qui ne sont pas présents dans l'autre ensemble (différence).

In [ ]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}
difference_set = set1.difference(set2)
difference_set

{1, 2}

clear() : Supprime tous les éléments de l'ensemble, le laissant vide.

In [ ]:
mon_set = {1, 2, 3}
mon_set.clear()
mon_set

set()

Notes :
  Les sets sont utiles lorsque vous avez besoin de travailler avec des ensembles d'éléments uniques, et ils offrent des méthodes efficaces pour effectuer des opérations ensemblistes.

#Les fonctions

En Python, une fonction est une séquence d'instructions nommée, qui peut être appelée avec un ensemble d'arguments pour effectuer une tâche spécifique. Voici quelques caractéristiques importantes des fonctions en Python :

1. Définition : Une fonction est définie à l'aide du mot-clé def, suivi du nom de la fonction et de ses paramètres, le tout suivi par un bloc d'instructions indentées.

In [ ]:
def ma_fonction(parametre1, parametre2):
    # Bloc d'instructions
    resultat = parametre1 + parametre2
    return resultat

2. Appel de fonction : Une fonction est appelée en utilisant son nom suivi de parenthèses contenant les arguments.

In [ ]:
resultat_final = ma_fonction(10, 20)

3. Paramètres : Les paramètres sont les valeurs que vous fournissez à une fonction lors de son appel. Une fonction peut avoir zéro, un ou plusieurs paramètres.

In [ ]:
def afficher_message(message):
    print(message)

afficher_message("Bonjour, Python!")

Bonjour, Python!


4. Valeurs de retour : Une fonction peut renvoyer une valeur à l'appelant à l'aide du mot-clé return.

In [ ]:
def multiplier_par_deux(nombre):
    resultat = nombre * 2
    return resultat

resultat_final = multiplier_par_deux(5)

5. Portée des variables : Les variables déclarées à l'intérieur d'une fonction sont locales à cette fonction, sauf si explicitement déclarées comme globales.

In [ ]:
def exemple():
    variable_locale = 10
    print(variable_locale)

exemple()

10


7. Fonctions intégrées : Python propose de nombreuses fonctions intégrées telles que print(), len(), range(), etc., qui sont disponibles sans nécessiter de définition explicite.

In [ ]:
longueur = len("Python")
longueur

6

8. Fonctions anonymes (lambda) : En plus des fonctions définies avec def, Python prend également en charge les fonctions anonymes définies avec le mot-clé lambda.

In [ ]:
carre = lambda x: x ** 2
resultat = carre(5)
resultat

25

Les fonctions sont des éléments fondamentaux de la programmation en Python, permettant d'organiser le code en blocs réutilisables et de favoriser la modularité.

#Exercices

1. Exercice 1: Calcul de Carré Écrivez une fonction appelée carre qui prend un nombre en argument et renvoie le carré de ce nombre.

In [ ]:
def carre(nombre) :
    c = nombre *4
    print(c)
carre(5)

20


2. Exercice 2: Concaténation de Chaînes Écrivez une fonction appelée concatener qui prend deux chaînes en argument et renvoie une seule chaîne qui est la concaténation des deux.

In [ ]:
def concatener(str1, str2) :
     resultat = str1 + str2
     print(resultat)
concatener ('joy', 'ce')

joyce


3. Exercice 3: Vérification de Nombre Pair Écrivez une fonction appelée est_pair qui prend un nombre en argument et renvoie True s'il est pair et False s'il est impair.

In [ ]:
def est_pair(nombre):
    return nombre % 2 == 0
est_pair(8)
est_pair(1)

False

4. Exercice 4: Somme de Nombres Écrivez une fonction appelée somme_nombres qui prend une liste de nombres en argument et renvoie la somme de ces nombres.

In [ ]:
def somme(liste):
    return sum(liste)

nombre = [1, 2,3,4]
somme(nombre)

10

5. Exercice 5: Calcul de Factorielle Écrivez une fonction appelée factorielle qui prend un entier positif en argument et renvoie sa factorielle. Utilisez une approche récursive.

In [ ]:
def factorielle(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorielle(n - 1)
n= int(input('mettez un nombre :'))
factorielle (n)

mettez un nombre :6


720

#les fonctions map et lambda

Les fonctions map et lambda sont souvent utilisées ensemble en Python pour appliquer une fonction à chaque élément d'une séquence (comme une liste) de manière concise et efficace. Voici une explication de chacune :

La fonction map : La fonction map permet d'appliquer une fonction à chaque élément d'une ou plusieurs séquences (listes, tuples, etc.) et renvoie un objet map. Cet objet peut être converti en une liste ou un autre type de séquence si nécessaire.

In [ ]:
nombres = [1, 2, 3, 4, 5]
carres = map(lambda x: x**2, nombres)
liste_carres = list(carres)
liste_carres

[1, 4, 9, 16, 25]

Ici, la fonction lambda x: x**2 calcule le carré de chaque nombre de la liste nombres, et la fonction map applique cette fonction à chaque élément de la liste.

La fonction lambda : La fonction lambda est une fonction anonyme définie en une seule ligne. Elle est souvent utilisée avec map pour définir rapidement une fonction simple.

In [ ]:
carres = map(lambda x: x**2, [1, 2, 3, 4, 5])
for carre in carres:
    print(carre)

1
4
9
16
25


La fonction lambda ici prend un argument x et renvoie x**2. C'est une manière concise de définir une petite fonction sans utiliser def.

En résumé, map applique une fonction à chaque élément d'une séquence, et lambda est souvent utilisé pour créer des fonctions simples à la volée. L'utilisation de ces deux concepts ensemble peut rendre le code plus lisible et compact lorsqu'on travaille avec des transformations sur des séquences.

#La programmation Orientée Objet (POO)

En Python, la programmation orientée objet (POO) repose sur des concepts clés tels que les classes et les objets. Voici quelques points importants à connaître :

1. Classes : Les classes sont des modèles pour créer des objets. Elles définissent les propriétés (attributs) et les comportements (méthodes) des objets.

2. Objets : Les objets sont des instances de classes. Chaque objet a ses propres valeurs d'attributs, mais partage les mêmes méthodes définies par sa classe.

3. Héritage : Python prend en charge l'héritage, permettant à une classe (sous-classe) de hériter des attributs et des méthodes d'une autre classe (super-classe). Cela favorise la réutilisation du code.

In [ ]:
class Animal:
    def manger(self):
        print("Je mange")

class Chat(Animal):
    def miauler(self):
        print("Miaou")

4. Encapsulation : La POO encourage l'encapsulation, limitant l'accès direct aux attributs d'un objet. On utilise souvent des méthodes pour accéder et modifier les attributs.

In [ ]:
class Voiture:
    def __init__(self, marque):
        self.marque = marque
        self.__vitesse = 0  # Attribut privé

    def accelerer(self):
        self.__vitesse += 10

    def obtenir_vitesse(self):
        return self.__vitesse

5. Polymorphisme : Python prend en charge le polymorphisme, permettant à des objets de différentes classes de répondre de manière similaire à une méthode.

In [ ]:
def faire_sonner(sonnable):
    sonnable.sonner()

class Telephone:
    def sonner(self):
        print("Riiing")

class Cloche:
    def sonner(self):
        print("Ding dong")

In [ ]:
class Eleve:
    def __init__(self,nom, age) :
        self.nom = nom
        self.age = age
    def Present(nom, age) :
        print(f"bonjour je suis {nom} j'ai {age} ans")

Eleve.Present('Jonathan', 20)

bonjour je suis Jonathan j'ai 20 ans


In [ ]:
class Papa :
    def __init__(self, nom, age) :
        self.nom = nom
        self.age = age
    def Salutation(nom) :
        print(f"salut je suis {nom}")
class Enfant (Famille) :
     def __init__(self, nom, age):
      pass
     def salutation (nom) :
        print(f"salut je suis {nom}")

Papa.Salutation ('john')
Enfant.salutation('julie')

salut je suis john
salut je suis julie


#Exercices

Exercice 1: Création d'une classe
Créez une classe Rectangle avec les attributs longueur et largeur. Ajoutez une méthode pour calculer la superficie du rectangle.

In [ ]:
class Rectangle:
    def __init__(self, longueur, largeur):
        self.longueur = longueur
        self.largeur = largeur

    def calculer_superficie(longueur,largeur):
        print(longueur *largeur)
resultat = Rectangle.calculer_superficie(20, 10)
resultat

200


Exercice 2: HéritageÉtendez la classe Rectangle en créant une sous-classe appelée Carre. Assurez-vous que la classe Carre hérite de la classe Rectangle et ajuste la méthode pour calculer la superficie en conséquence.

In [ ]:

class Rectangle:
    def __init__(self, longueur, largeur):
        self.longueur = longueur
        self.largeur = largeur

    def calculer_superficie(longueur,largeur):
        print(longueur *largeur)

class Carre(Rectangle):
    def __init__(self, cote):
        super().__init__(cote)

    def calculer_superficie(cote):
        print(cote * cote)

Carre.calculer_superficie(20)

400


Exercice 3: EncapsulationCréez une classe CompteBancaire avec les attributs solde et titulaire. Encapsulez l'attribut solde et ajoutez des méthodes pour déposer et retirer de l'argent.

In [ ]:
class CompteBancaire:
    def __init__(self, titulaire, solde=0):
        self.titulaire = titulaire
        self.solde = solde

    def deposer(montant, solde):
        print(solde+montant)
    def retirer ( montant,solde) :
        if montant <= solde:
            print(solde - montant)
        else :
            print('votre solde est insuffisant')
CompteBancaire.deposer(100,0)
CompteBancaire.retirer (50,100)

100
50


Exercice 4: PolymorphismeDéfinissez une interface Forme avec une méthode aire(). Implémentez cette interface dans les classes Cercle et Triangle. Créez une fonction qui prend une liste de formes et affiche l'aire de chacune.

In [ ]:
from abc import ABC, abstractmethod

class Forme(ABC):
    @abstractmethod
    def aire(self):
        pass

class Cercle(Forme):
    def __init__(self, rayon):
        self.rayon = rayon

    def aire(self):
        return 3.14 * self.rayon**2

class Triangle(Forme):
    def __init__(self, base, hauteur):
        self.base = base
        self.hauteur = hauteur

    def aire(self):
        return 0.5 * self.base * self.hauteur

def afficher_aires(formes):
    for forme in formes:
        print(f"Aire de la forme: {forme.aire()}")

# Exemple d'utilisation
cercle = Cercle(5)
triangle = Triangle(4, 8)

afficher_aires([cercle, triangle])

Aire de la forme: 78.5
Aire de la forme: 16.0


Exercice 5: Méthodes spécialesAjoutez des méthodes spéciales à la classe Rectangle pour permettre l'addition de deux rectangles (en ajoutant leurs côtés respectifs) et la comparaison de deux rectangles (en comparant leurs superficies).

In [ ]:
class Rectangle:
    def __init__(self, longueur, largeur):
        self.longueur = longueur
        self.largeur = largeur

    def calculer_superficie(self):
        return self.longueur * self.largeur

    def __add__(self, autre_rectangle):
        return Rectangle(self.longueur + autre_rectangle.longueur, self.largeur + autre_rectangle.largeur)

    def __eq__(self, autre_rectangle):
        return self.calculer_superficie() == autre_rectangle.calculer_superficie()

#Les exceptions

En Python, les exceptions sont des événements qui se produisent lors de l'exécution d'un programme, indiquant qu'une erreur s'est produite. Voici quelques concepts clés liés aux exceptions en Python :

1. Levée d'exception : Vous pouvez lever une exception en utilisant le mot-clé raise. Cela est utile pour signaler qu'une condition d'erreur particulière a été rencontrée.

In [ ]:
raise ValueError("Ceci est un message d'erreur")

ValueError: ignored

2. Gestion d'exception avec try et except : Vous pouvez entourer un bloc de code potentiellement problématique avec try et except pour gérer les exceptions.

In [ ]:
print(10/0)

ZeroDivisionError: division by zero

In [ ]:
try:
    # Code potentiellement problématique
    resultat = 10 / 0
except ZeroDivisionError:
    print("Division par zéro détectée")

Division par zéro détectée


3. Clause else dans le bloc try : Vous pouvez utiliser la clause else pour spécifier un bloc de code qui ne sera exécuté que si aucune exception n'est levée dans le bloc try.

In [ ]:
try:
    # Code potentiellement problématique
    resultat = 10 / 2
except ZeroDivisionError:
    print("Division par zéro détectée")
else:
    print("Aucune exception n'a été levée")

Aucune exception n'a été levée


4. Clause finally dans le bloc try : La clause finally permet de spécifier un bloc de code qui sera exécuté quelle que soit la présence ou non d'une exception.

In [ ]:
try:
    # Code potentiellement problématique
    resultat = 10 / 0
except ZeroDivisionError:
    print("Division par zéro détectée")
finally:
    print("Ce code sera toujours exécuté")

Division par zéro détectée
Ce code sera toujours exécuté


5. Exceptions personnalisées : Vous pouvez créer vos propres exceptions en définissant une nouvelle classe qui hérite de la classe Exception.

In [ ]:
class MonErreurPersonnalisee(Exception):
    pass

raise MonErreurPersonnalisee("Ceci est un message d'erreur personnalisé")

MonErreurPersonnalisee: ignored

6. Gestion multiple d'exceptions : Vous pouvez gérer plusieurs types d'exceptions dans le même bloc except.

In [ ]:
try:
    # Code potentiellement problématique
    resultat = 10 / 0
except (ZeroDivisionError, ValueError):
    print("Une erreur s'est produite")

Une erreur s'est produite


Ces concepts constituent une base solide pour travailler avec les exceptions en Python, permettant une gestion robuste des erreurs dans vos programmes.

#Exercices

Exercice 1: Gestion d'une division par zéroÉcrivez un programme qui demande à l'utilisateur de saisir deux nombres, puis effectue la division du premier nombre par le deuxième. Utilisez la gestion des exceptions pour gérer le cas où l'utilisateur tente de diviser par zéro.

In [ ]:
nombre = int(input('nombre 1 :'))
nombre2 = int(input('nombre 2 :'))

try :
    print(nombre/nombre2)
except(ZeroDivisionError) :
    print("erreur d'opérations ")

nombre 1 :10
nombre 2 :0
erreur d'opérations 


Exercice 2: Conversion de chaîne en entierÉcrivez une fonction qui prend une chaîne en entrée, tente de la convertir en entier, et renvoie le résultat. Utilisez la gestion des exceptions pour gérer le cas où la conversion échoue.

In [ ]:
Chaine = '12345'
#print(int(Chaine))
try :
    print(int(Chaine))
except (e) :
    print('Erreur')

12345


Exercice 3: Gestion d'un fichier manquantÉcrivez un programme qui tente de lire le contenu d'un fichier dont le nom est fourni par l'utilisateur. Utilisez la gestion des exceptions pour gérer le cas où le fichier n'existe pas.

#Modules et bibliothèques

En Python, les termes "module" et "bibliothèque" sont souvent utilisés de manière interchangeable, mais ils ont des significations légèrement différentes.

Module :Un module en Python est un fichier contenant du code Python. Ce fichier peut contenir des définitions de fonctions, de classes et de variables.Les modules sont utilisés pour organiser et structurer le code en le divisant en fichiers plus petits et plus gérables.Vous pouvez importer des modules dans d'autres scripts Python en utilisant l'instruction import.Exemple :

In [ ]:
# module.py
def fonction_du_module():
    print("Fonction du module appelée")

# script.py
#import module
#module.fonction_du_module()

Bibliothèque :Une bibliothèque en Python est un ensemble de modules qui résolvent un ensemble de problèmes ou fournissent des fonctionnalités spécifiques.Les bibliothèques sont généralement des ensembles de modules liés par une fonctionnalité ou un objectif commun.Exemples de bibliothèques en Python incluent NumPy pour le calcul numérique, requests pour les requêtes HTTP, et tkinter pour l'interface graphique.Exemple :

In [ ]:
import requests
response = requests.get("https://www.example.com")

#La bibliothèque standard

La bibliothèque standard de Python est une collection de modules et de packages inclus avec chaque installation de Python. Ces modules offrent une gamme étendue de fonctionnalités pour des tâches courantes. Voici quelques-unes des bibliothèques standard les plus couramment utilisées :

os : Fournit des fonctionnalités pour interagir avec le système d'exploitation, tels que la manipulation de fichiers, la gestion des répertoires, etc.

In [ ]:
import os

def lister_fichiers(repertoire):
    print(f"Liste des fichiers dans le répertoire : {repertoire}")
    for nom_fichier in os.listdir(repertoire):
        chemin_fichier = os.path.join(repertoire, nom_fichier)
        if os.path.isfile(chemin_fichier):
            taille = os.path.getsize(chemin_fichier)
            print(f"{nom_fichier} - {taille} octets")

# Exemple d'utilisation
repertoire_courant = os.getcwd()
lister_fichiers(repertoire_courant)

Liste des fichiers dans le répertoire : /content


datetime : Permet de manipuler des objets de date et d'heure, et offre des fonctionnalités pour formater et analyser les dates.

In [ ]:
from datetime import datetime, timedelta

# Obtenir la date et l'heure actuelles
maintenant = datetime.now()
print("Date et heure actuelles :", maintenant)

# Formater la date
format_date = maintenant.strftime("%Y-%m-%d %H:%M:%S")
print("Date formatée :", format_date)

# Créer une date spécifique
date_personnalisee = datetime(2023, 1, 1)
print("Date personnalisée :", date_personnalisee)

# Opérations sur les dates
demain = maintenant + timedelta(days=1)
print("Demain à la même heure :", demain)

# Différence entre deux dates
difference = demain - maintenant
print("Différence de temps :", difference)
print("Différence en jours :", difference.days)

Date et heure actuelles : 2023-12-29 09:43:36.433254
Date formatée : 2023-12-29 09:43:36
Date personnalisée : 2023-01-01 00:00:00
Demain à la même heure : 2023-12-30 09:43:36.433254
Différence de temps : 1 day, 0:00:00
Différence en jours : 1


math : Fournit des fonctions mathématiques, telles que sqrt (racine carrée), sin (sinus), cos (cosinus), etc.

In [ ]:
import math

# Fonctions trigonométriques
angle = math.radians(45)  # Convertir 45 degrés en radians
sin_value = math.sin(angle)
cos_value = math.cos(angle)
tan_value = math.tan(angle)

print(f"Sine de 45 degrés : {sin_value}")
print(f"Cosine de 45 degrés : {cos_value}")
print(f"Tangente de 45 degrés : {tan_value}")

# Fonctions logarithmiques
log_value = math.log(10, 2)  # Logarithme de 10 en base 2
sqrt_value = math.sqrt(25)   # Racine carrée de 25

print(f"Logarithme de 10 en base 2 : {log_value}")
print(f"Racine carrée de 25 : {sqrt_value}")

# Constantes
print(f"La constante pi : {math.pi}")
print(f"La constante d'Euler : {math.e}")

Sine de 45 degrés : 0.7071067811865475
Cosine de 45 degrés : 0.7071067811865476
Tangente de 45 degrés : 0.9999999999999999
Logarithme de 10 en base 2 : 3.3219280948873626
Racine carrée de 25 : 5.0
La constante pi : 3.141592653589793
La constante d'Euler : 2.718281828459045


random : Permet de générer des nombres aléatoires.

In [ ]:

import random

# Générer un nombre aléatoire entre 0 et 1
nombre_aleatoire = random.random()
print(f"Nombre aléatoire entre 0 et 1 : {nombre_aleatoire}")

# Générer un nombre entier aléatoire dans une plage spécifique
nombre_entier = random.randint(1, 10)
print(f"Nombre entier aléatoire entre 1 et 10 : {nombre_entier}")

# Sélection aléatoire d'un élément dans une liste
liste = [1, 2, 3, 4, 5]
element_aleatoire = random.choice(liste)
print(f"Élément aléatoire de la liste : {element_aleatoire}")

# Mélanger une liste aléatoirement
random.shuffle(liste)
print(f"Liste mélangée : {liste}")

Nombre aléatoire entre 0 et 1 : 0.1981652191940696
Nombre entier aléatoire entre 1 et 10 : 2
Élément aléatoire de la liste : 2
Liste mélangée : [2, 4, 3, 5, 1]


json : Facilite la sérialisation et la désérialisation de données au format JSON.

In [ ]:
import json

# Créer un dictionnaire Python
donnees = {
    "nom": "John Doe",
    "age": 30,
    "ville": "Exampleville",
    "est_etudiant": False,
    "notes": [90, 85, 88]
}

# Convertir le dictionnaire en format JSON (encodage)
donnees_json = json.dumps(donnees, indent=2)  # indent pour une sortie formatée
print("Données au format JSON :\n", donnees_json)

# Écrire les données JSON dans un fichier
with open("donnees.json", "w") as fichier:
    json.dump(donnees, fichier, indent=2)

# Lire les données JSON à partir d'un fichier (décodage)
with open("donnees.json", "r") as fichier:
    donnees_chargees = json.load(fichier)

print("\nDonnées chargées à partir du fichier JSON :\n", donnees_chargees)

Données au format JSON :
 {
  "nom": "John Doe",
  "age": 30,
  "ville": "Exampleville",
  "est_etudiant": false,
  "notes": [
    90,
    85,
    88
  ]
}

Données chargées à partir du fichier JSON :
 {'nom': 'John Doe', 'age': 30, 'ville': 'Exampleville', 'est_etudiant': False, 'notes': [90, 85, 88]}


urllib : Fournit des fonctionnalités pour travailler avec les URL, telles que l'ouverture d'URL et la gestion des requêtes.

In [ ]:
from urllib.request import urlopen

# Exemple de requête GET
url = "https://www.example.com"
response = urlopen(url)

# Lire le contenu de la réponse
contenu = response.read().decode('utf-8')

# Afficher le contenu
print(contenu)

# Fermer la réponse
response.close()

<!doctype html>
<html>
<head>
    <title>Example Domain</title>

    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style type="text/css">
    body {
        background-color: #f0f0f2;
        margin: 0;
        padding: 0;
        font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
        
    }
    div {
        width: 600px;
        margin: 5em auto;
        padding: 2em;
        background-color: #fdfdff;
        border-radius: 0.5em;
        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);
    }
    a:link, a:visited {
        color: #38488f;
        text-decoration: none;
    }
    @media (max-width: 700px) {
        div {
            margin: 0 auto;
            width: auto;
        }
    }
    </style>    
</head>

<body>
<div>
    <h1>Example Domain</h1>
    <p>This domai

re : Introduit des expressions régulières pour la manipulation de chaînes de caractères.

collections : Propose des alternatives avancées aux types de données intégrés, telles que OrderedDict, defaultdict, Counter, etc.

sys : Fournit des fonctionnalités liées au système, telles que les arguments de ligne de commande et les appels système

In [ ]:
import sys

# Afficher la version de Python
print("Version de Python :", sys.version)

# Afficher la plateforme
print("Plateforme :", sys.platform)

# Afficher le chemin de recherche des modules
print("Chemin de recherche des modules :", sys.path)

# Afficher les arguments de ligne de commande
print("Arguments de la ligne de commande :", sys.argv)

# Terminer le programme avec un code de sortie
sys.exit(0)

Version de Python : 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Plateforme : linux
Chemin de recherche des modules : ['/content', '/env/python', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.10/dist-packages/IPython/extensions', '/root/.ipython']
Arguments de la ligne de commande : ['/usr/local/lib/python3.10/dist-packages/colab_kernel_launcher.py', '-f', '/root/.local/share/jupyter/runtime/kernel-eae1d268-efab-405b-baae-dc17f04341dc.json']


SystemExit: ignored

/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


socket : Permet de travailler avec les sockets pour la communication réseau.

In [ ]:
import socket

# Configuration du serveur
serveur = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
serveur.bind(("127.0.0.1", 8888))
serveur.listen(1)

print("Attente de connexion...")
connexion, adresse_client = serveur.accept()
print(f"Connexion établie avec {adresse_client}")

# Recevoir des données du client
donnees = connexion.recv(1024)
print(f"Données reçues du client : {donnees.decode('utf-8')}")

# Fermer la connexion
connexion.close()
serveur.close()

Attente de connexion...


KeyboardInterrupt: ignored

In [ ]:
import socket

# Configuration du client
client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client.connect(("127.0.0.1", 8888))

# Envoyer des données au serveur
donnees = "Bonjour, serveur!"
client.sendall(donnees.encode('utf-8'))

# Fermer la connexion
client.close()

#Pip et Pypi

pip est un gestionnaire de paquets pour Python. Il est utilisé pour installer et gérer des bibliothèques externes, également appelées paquets ou modules, qui ne font pas partie de la bibliothèque standard de Python. Avec pip, vous pouvez facilement installer, mettre à jour et désinstaller des paquets Python.

Quelques commandes pip couramment utilisées :

pip install package_name: Installe un paquet Python.

pip install -r requirements.txt: Installe les paquets répertoriés dans un fichier requirements.txt.

pip uninstall package_name: Désinstalle un paquet Python.

pip freeze > requirements.txt: Exporte la liste des paquets installés avec leurs versions dans un fichier requirements.txt.

PyPI (Python Package Index) :PyPI est le référentiel officiel en ligne pour les paquets Python. Il contient des milliers de paquets que les développeurs peuvent utiliser et partager avec la communauté Python. Lorsque vous utilisez pip install, le gestionnaire de paquets va chercher le paquet sur PyPI et l'installer sur votre système.

#Python pour aller loin

1. Le Web : Il existe plusieurs frameworks web populaires en Python qui facilitent le développement d'applications web. Voici quelques-uns des frameworks les plus utilisés :

a. Django : Un framework web complet et haut niveau qui favorise la rapidité de développement et le principe de "batteries incluses". Il propose un ORM intégré, une administration automatique, un système de gestion des URL, et bien plus encore.

b. Flask : Un framework web léger et extensible qui offre une grande flexibilité. Flask est souvent utilisé pour les petites et moyennes applications web. Il ne fournit que les éléments essentiels, mais est extensible avec des extensions.

c. FastAPI : Un framework moderne et rapide pour la création d'API RESTful basées sur Python 3.7+. Il utilise des annotations de type pour une documentation automatique et une validation des données.

d. Bottle : Un micro-framework simple et léger, souvent utilisé pour les petites applications ou les projets où la simplicité est essentielle. Il ne nécessite pas de dépendances externes.

e. Pyramid : Un framework web flexible qui peut être utilisé pour des applications de petite à grande envergure. Il propose une approche modulaire, permettant aux développeurs de choisir les composants dont ils ont besoin.

Pour la sécurité informatique en Python, plusieurs frameworks et bibliothèques sont disponibles pour aider à effectuer des tâches spécifiques liées à la sécurité et à la cyber-sécurité. Voici quelques-uns d'entre eux :

1. Scapy : Une bibliothèque puissante dédiée à la manipulation de paquets réseau. Scapy permet la création, l'envoi, la capture et l'analyse de paquets réseau.

2. OWASP ZAP (Zed Attack Proxy) : Un projet de sécurité automatisé pour trouver des vulnérabilités dans les applications web. Il offre des fonctionnalités d'exploration, de recherche de vulnérabilités, et de rapports automatisés.

3. ZAPPyCryptoDome : Une bibliothèque de chiffrement qui propose divers algorithmes cryptographiques, y compris le chiffrement symétrique et asymétrique.

4. Cryptography : Une bibliothèque Python pour implémenter divers protocoles cryptographiques, tels que TLS.

5. SQLmap : Un outil automatisé d'injection SQL et de test de sécurité des bases de données. Il est utilisé pour détecter et exploiter les vulnérabilités d'injection SQL.

6. Scikitlearn : Bien que principalement connu comme un framework pour l'apprentissage automatique, Scikit-learn peut également être utilisé pour des tâches de détection d'anomalies et d'analyse de comportement malveillant.

Pour l'analyse des données en Python, il existe plusieurs bibliothèques et frameworks puissants. Voici quelques-uns des plus populaires :

1. NumPy : Une bibliothèque fondamentale pour le calcul numérique en Python. NumPy offre des structures de données telles que les tableaux (arrays) et des fonctions pour effectuer des opérations mathématiques sur ces tableaux.

2. Pandas : Une bibliothèque puissante pour la manipulation et l'analyse des données. Elle offre des structures de données flexibles, notamment les DataFrames, ainsi que des outils pour le nettoyage, la transformation et l'analyse des données.

3. Matplotlib : Une bibliothèque de visualisation permettant de créer des graphiques 2D et 3D. Matplotlib est souvent utilisé conjointement avec NumPy et pandas pour visualiser les données.

4. Seaborn : Une extension de Matplotlib qui simplifie la création de graphiques statistiques attrayants. Seaborn est particulièrement utile pour explorer les relations dans les données.

5. SciPy : Construit sur NumPy, SciPy étend ses fonctionnalités en fournissant des outils pour l'optimisation, l'algèbre linéaire, l'intégration, et bien plus encore. Il est souvent utilisé en conjonction avec NumPy pour des analyses scientifiques plus avancées.
6. scikit-learn : Une bibliothèque d'apprentissage automatique qui offre des outils pour la classification, la régression, le clustering, la réduction de dimensionnalité,

7. Statsmodels : Une bibliothèque pour estimer et tester des modèles statistiques. Elle offre des fonctionnalités pour les régressions, les séries temporelles, et divers tests statistiques.

Dans le domaine de l'intelligence artificielle (IA) en Python, plusieurs bibliothèques et frameworks sont couramment utilisés. Voici quelques-uns des plus populaires :TensorFlow : Une bibliothèque d'apprentissage profond (deep learning) développée par Google. TensorFlow est utilisé pour créer des modèles de réseaux neuronaux, y compris les réseaux de neurones profonds.Site Web :

1. TensorFlowPyTorch : Un framework d'apprentissage profond développé par Facebook. PyTorch est apprécié pour sa flexibilité et sa facilité d'utilisation, en particulier dans le cadre de la recherche en apprentissage profond.

2. Keras : Une interface haut niveau qui peut être utilisée avec des bibliothèques de backend comme TensorFlow et Theano. Keras simplifie la création et l'expérimentation avec des modèles d'apprentissage profond.

3. scikit-learn : Outre son utilisation pour l'analyse de données, scikit-learn propose des outils pour l'apprentissage machine, y compris des algorithmes de classification, de régression, de clustering, et plus encore.

4. NLTK (Natural Language Toolkit) : Une bibliothèque pour le traitement du langage naturel. NLTK offre des outils pour la tokenisation, la lemmatisation, la classification de texte, et d'autres tâches liées au langage naturel.

5. OpenCV : Une bibliothèque de vision par ordinateur qui offre des outils pour le traitement d'images et la vision par ordinateur. Elle est souvent utilisée dans des applications d'IA liées à la vision.

6. Gensim : Une bibliothèque pour le traitement de texte et la modélisation de sujets. Gensim est souvent utilisé pour l'analyse de texte et la création de modèles de plongement de mots.Site Web : Gensim

#Exercises pour Évaluer le niveau

Vérification de Palindrome : Écrivez une fonction qui vérifie si une chaîne de caractères est un palindrome (se lit de la même façon de gauche à droite et de droite à gauche).

In [ ]:
def palindrome(s) :
    if s == s[::-1] :
        print('is palandrome')
    else:
        print('is not')
palindrome ('papa')

is not


Liste des Carrés : Écrivez une fonction qui prend une liste de nombres en entrée et renvoie une nouvelle liste contenant les carrés de chaque nombre.

In [ ]:
def carre(n) :
    r = map(lambda x:x**2, n)
    print(list(r))
no = [1, 2,3,4]
carre(no)

[1, 4, 9, 16]


Comptage des Voyelles : Écrivez une fonction qui prend une chaîne de caractères en entrée et renvoie le nombre de voyelles présentes dans cette chaîne.

In [ ]:
def compter_voyelles(chaine):
    voyelles = "aeiouAEIOU"
    nombre_voyelles = sum(1 for char in chaine if char in voyelles)
    return nombre_voyelles


chaine_test = "Hello World"
resultat = compter_voyelles(chaine_test)
print(f"Le nombre de voyelles dans '{chaine_test}' est : {resultat}")

Le nombre de voyelles dans 'Hello World' est : 3


Tri de Liste : Écrivez une fonction qui trie une liste d'entiers de manière croissante.

In [ ]:
def tri_croissant(liste):
    return sorted(liste)


liste_non_triee = [4, 1, 8, 3, 5]
liste_triee = tri_croissant(liste_non_triee)
print("Liste non triée :", liste_non_triee)
print("Liste triée de manière croissante :", liste_triee)

Liste non triée : [4, 1, 8, 3, 5]
Liste triée de manière croissante : [1, 3, 4, 5, 8]


Conversion de Température : Écrivez une fonction qui convertit une température de Celsius à Fahrenheit (la formule est ( F = \frac{9}{5}C + 32 )).

In [ ]:
def celsius_en_fahrenheit(celsius):
    fahrenheit = (celsius * 9/5) + 32
    return fahrenheit


temperature_celsius = 32
temperature_fahrenheit = celsius_en_fahrenheit(temperature_celsius)
print(f"{temperature_celsius} degrés Celsius équivalent à {temperature_fahrenheit} degrés Fahrenheit.")

32 degrés Celsius équivalent à 89.6 degrés Fahrenheit.


Générateur de Mot de Passe : Écrivez une fonction qui génère un mot de passe aléatoire de longueur donnée.

In [ ]:
import random
import string

def generer_mot_de_passe(longueur):
    caracteres = string.ascii_letters + string.digits + string.punctuation
    mot_de_passe = ''.join(random.choice(caracteres) for _ in range(longueur))
    return mot_de_passe


longueur_mot_de_passe = 10
mot_de_passe_genere = generer_mot_de_passe(longueur_mot_de_passe)
print(f"Mot de passe généré : {mot_de_passe_genere}")

Mot de passe généré : 5SDKZLOP%>


Manipulation de Dictionnaire : Créez un dictionnaire avec des informations sur une personne (nom, âge, ville, etc.) et écrivez des fonctions pour accéder et mettre à jour ces informations.

In [ ]:

personne = {
    'nom': 'John Doe',
    'age': 30,
    'ville': 'VilleX',
    'profession': 'Ingénieur'
}

# Fonction pour accéder aux informations
def obtenir_information(info):
    return personne.get(info, "L'information n'est pas disponible")

# Fonction pour mettre à jour les informations
def mettre_a_jour_information(cle, nouvelle_valeur):
    personne[cle] = nouvelle_valeur

# Exemple d'utilisation
print("Nom de la personne:", obtenir_information('nom'))
print("Âge de la personne:", obtenir_information('age'))

mettre_a_jour_information('age', 31)
print("Nouvel âge de la personne:", obtenir_information('age'))

Nom de la personne: John Doe
Âge de la personne: 30
Nouvel âge de la personne: 31


Pierre feuille ciseaux

In [ ]:
import random

def choix_ordinateur():
    return random.choice(["pierre", "papier", "ciseaux"])

def verifier_gagnant(choix_joueur, choix_ordi):
    if choix_joueur == choix_ordi:
        return "Égalité!"
    elif (
        (choix_joueur == "pierre" and choix_ordi == "ciseaux") or
        (choix_joueur == "papier" and choix_ordi == "pierre") or
        (choix_joueur == "ciseaux" and choix_ordi == "papier")
    ):
        return "Vous avez gagné!"
    else:
        return "L'ordinateur a gagné!"

def jouer_pierre_feuille_ciseaux():
    print("Bienvenue au jeu de Pierre-Papier-Ciseaux!")
    choix_joueur = input("Choisissez pierre, papier ou ciseaux: ").lower()

    if choix_joueur not in ["pierre", "papier", "ciseaux"]:
        print("Choix invalide. Veuillez choisir pierre, papier ou ciseaux.")
        return

    choix_ordi = choix_ordinateur()

    print(f"L'ordinateur a choisi {choix_ordi}.")
    resultat = verifier_gagnant(choix_joueur, choix_ordi)
    print(resultat)

# Exécuter le jeu
jouer_pierre_feuille_ciseaux()

Bienvenue au jeu de Pierre-Papier-Ciseaux!
Choisissez pierre, papier ou ciseaux: Pierre
L'ordinateur a choisi pierre.
Égalité!


#Operations mathématiques

Suite de Fibonacci : Écrivez une fonction pour générer les n premiers termes de la suite de Fibonacci.

In [ ]:
def fibonacci(n):
    fib = [0, 1]
    while len(fib) < n:
        fib.append(fib[-1] + fib[-2])
    return fib
fibonacci(10)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

Nombre Premier : Écrivez une fonction pour vérifier si un nombre est premier.

In [ ]:
def est_premier(nombre):
    if nombre < 2:
        return False
    for i in range(2, int(nombre**0.5) + 1):
        if nombre % i == 0:
            return False
    return True
est_premier(2)

True

PGCD : Écrivez une fonction pour calculer le Plus Grand Commun Diviseur (PGCD) de deux nombres

In [ ]:
def pgcd(a, b):
    while b:
        a, b = b, a % b
    return a
pgcd(20, 8)

4

Nombre Parfait : Écrivez une fonction pour vérifier si un nombre est parfait (la somme de ses diviseurs propres est égale à lui-même).

In [ ]:
def est_parfait(nombre):
    diviseurs = [i for i in range(1, nombre) if nombre % i == 0]
    return sum(diviseurs) == nombre
est_parfait (6)

True

Calcul de Puissance : Écrivez une fonction pour calculer une puissance, c'est-à-dire (a^n).

In [ ]:
def puissance(a, n):
    return a ** n

base = 2
exposant = 3
resultat = puissance(base, exposant)
print(f"{base}^{exposant} = {resultat}")

2^3 = 8


Test de Palindrome Numérique : Écrivez une fonction pour vérifier si un nombre est un palindrome (se lit de la même façon de gauche à droite et de droite à gauche).

In [ ]:
def est_palindrome(nombre):
    str_nombre = str(nombre)
    return str_nombre == str_nombre[::-1]


nombre_test = 12321
if est_palindrome(nombre_test):
    print(f"{nombre_test} est un palindrome.")
else:
    print(f"{nombre_test} n'est pas un palindrome.")

12321 est un palindrome.


#Numeric Python ( NumPy)

Site officiel

https://numpy.org/

NumPy est une bibliothèque en Python qui prend en charge les tableaux multidimensionnels et les opérations mathématiques pour les manipuler de manière efficace. Elle offre des fonctionnalités pour effectuer des calculs numériques, des opérations sur les tableaux, et elle est largement utilisée dans le domaine de la science des données, de l'apprentissage automatique et d'autres domaines liés aux calculs numériques.

Comment l'importer :

In [70]:
import numpy as np

Créé un tableau multidimensionnel :

In [72]:
np.array([1, 2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

Cela crée un tableau NumPy unidimensionnel avec les valeurs 1, 2, 3, 4, 5. Vous pouvez également créer des tableaux multidimensionnels en passant des listes imbriquées à la fonction np.array().

Autres méthodes pour créé des tableaux :

1. np.array() : À partir d'une liste ou d'un tuple.

In [73]:
tableau = np.array([1, 2, 3, 4, 5])
tableau

array([1, 2, 3, 4, 5])

2. np.zeros() : Pour créer un tableau de zéros.

In [74]:
tableau_zeros = np.zeros(5)
tableau_zeros

array([0., 0., 0., 0., 0.])

3. np.ones() : Pour créer un tableau de uns.

In [75]:

tableau_ones = np.ones(5)
tableau_ones

array([1., 1., 1., 1., 1.])

4. np.arange() : Pour créer un tableau avec une séquence d'entiers.

In [76]:
tableau_sequence = np.arange(1, 10, 2)
tableau_sequence

array([1, 3, 5, 7, 9])

5. np.linspace() : Pour créer un tableau avec une séquence d'éléments espacés de manière égale.

In [78]:
tableau_espacement = np.linspace(0, 1, 5)
tableau_espacement

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

6. np.random.rand() : Pour créer un tableau avec des valeurs aléatoires entre 0 et 1.

In [79]:
tableau_random = np.random.rand(3, 3)
tableau_random

array([[0.22926799, 0.22129309, 0.51188177],
       [0.73889417, 0.33319628, 0.17307428],
       [0.74084721, 0.65309661, 0.61411336]])

#Les opérations Mathématiques avec NumPy

NumPy offre un large éventail d'opérations mathématiques pour travailler avec des tableaux. Voici quelques exemples d'opérations couramment utilisées :

- Addition, Soustraction, Multiplication, Division :

In [89]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

addition = a + b
soustraction = a - b
multiplication = a * b
division = a / b

print(addition)
print(soustraction)
print(multiplication)
print(division)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


- Fonctions mathématiques universelles (ufunc) :

In [91]:
tableau = np.array([1, 2, 3])

carre = np.square(tableau)  # Carré de chaque élément
racine_carree = np.sqrt(tableau)  # Racine carrée de chaque élément
exponentielle = np.exp(tableau)  # Exponentielle de chaque élément
print(carre)
print(racine_carree)
print(exponentielle)

[1 4 9]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]


- Produit scalaire :

In [93]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

produit_scalaire = np.dot(a, b)
produit_scalaire

32

- Somme, Moyenne, Minimum, Maximum :

In [96]:

tableau = np.array([1, 2, 3, 4, 5])

somme = np.sum(tableau)
moyenne = np.mean(tableau)
minimum = np.min(tableau)
maximum = np.max(tableau)

print(moyenne)
print(maximum)
print(minimum)
print(somme)

3.0
5
1
15


- Fonctions de manipulation de tableaux :

np.shape(): Retourne la forme (nombre de lignes et de colonnes) du tableau.

In [105]:
array = np.array([1, 2, 3, 4, 6, 7, 8])

# Obtenir la forme du tableau
forme_tableau = array.shape

# Afficher la forme
print(forme_tableau)

(7,)


np.reshape(): Remodèle le tableau.

In [104]:
tableau = np.array([1, 2,3,4,5,6,7,8])
t = tableau.reshape (2, 4)
t

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

np.concatenate(): Concatène deux tableaux.

In [100]:
a = np.array([1, 2,4,3])
b = np.array([5, 6,7,8])
c = np.concatenate((a, b))
c

array([1, 2, 4, 3, 5, 6, 7, 8])